### ISSUE TITLE
Save Feedback: 🐛 Invalid fields in applicant section produces invalid fields in the IR section 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/dac-ui#188] opened 2021-07-08 18:25 UTC
Example: https://drive.google.com/file/d/13VEIyxjK4M2NSTz3brgQB1lcaoNWb1zX/view

## Expected behaviour 
If i have not  yet interacted with a field, it should not tell me its invalid.

**Comment by caravinci** [comment] 2021-07-08 18:43
Debugging note to self: it seems the clicking on the field was mistaken by the persistence logic, without differentiating that though the field was touched the value didn't change from blank.

**Comment by rosibaj** [comment] 2021-07-08 18:45
@caravinci to clarify the video, i didnt click on the field.  I clicked just on that section (field itself wasnt clicked, or touched in any way)

**Comment by caravinci** [comment] 2021-07-08 19:22
Initially I had mistakenly confused the offending field for the one being clicked and focused on 0:35 (notice the blue halo around it). That shouldn't have triggered validation errors, as the value wasn't changed at all.

![image](https://user-images.githubusercontent.com/2107110/124978478-d77ed480-dfff-11eb-9e48-d6fbd0519957.png)

-----
However I realise now the field is one in the next section, which hasn't even been touched at all... which you're 100% right is a big ol' `WHY????`. 
Apologies... In either case, it's a bad bug, and I'll squash it. 🥾

**Comment by kcullion** [comment] 2021-07-08 20:04
@caravinci @rosibaj I found this was the case with the First Name field too....so perhaps something more is happening between these two sections. 
![image](https://user-images.githubusercontent.com/18424138/124983588-23347c80-e006-11eb-9dfd-a7febc777d8b.png)

**Comment by caravinci** [comment] 2021-07-08 20:18
Thanks. that does help troubleshooting. more patterns to attempt replicating, to see if I figure out what's going on here 🤞

**Comment by caravinci** [comment] 2021-07-08 22:59
Moving to "code review" status as an interim status while validating the recent API changes may have resolved the problem. Will move back to "in progress" if these persist.

**Comment by caravinci** [comment] 2021-07-09 13:29
Can confirm the issue is UI side only, and will have a solution in the next short while.

**Comment by rosibaj** [comment] 2021-07-13 20:05
Tested Jul 13, 2021
- no unintended local validations observed as navigating/editing between sections. 
thank you @caravinci !!

**Closed** 2021-07-21 18:10 UTC
Labels: 0.14.0, bug
